using Discord;
using Discord.WebSocket;

using Inquisition.Logging;
using Inquisition.Services;

using System;
using System.Threading.Tasks;

namespace Inquisition.Handlers
{
    public class EventHandler
    {
        private readonly DiscordSocketClient _client;
		private readonly EventService _eventService;
        private readonly ILogger<EventHandler> _logger;
        private readonly ConversionHandler _conversionHandler;

		public EventHandler(
            DiscordSocketClient client,
            EventService eventService,
            ILogger<EventHandler> logger,
            ConversionHandler conversionHandler)
		{
			_client = client;
            _eventService = eventService;
            _logger = logger;
            _conversionHandler = conversionHandler;

			_client.Log += Log;
			_client.Ready += Ready;

			SubscribeToAuditService();
		}

		private Task Log(LogMessage logMessage)
        {
			// Invalid OpCode errors generated by opus.dll library
			// can be ignored aparently...
			if (!logMessage.Message.Contains("OpCode"))
			{
                _logger.LogInformation(logMessage.Source, logMessage.Message);
			}

			return Task.CompletedTask;
        }

#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        private async Task Ready()
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            Task.Run(() =>
			{
                _logger.LogInformation("Starting user registration...");

				try
				{
					foreach (SocketGuild guild in _client.Guilds)
					{
						foreach (SocketGuildUser user in guild.Users)
						{
							if (!user.IsBot)
							{
								_conversionHandler.AddUser(user);
							}
						}
					}

				}
				catch (Exception e)
				{
                    _logger.LogError(e);
				}
				finally
				{
                    _logger.LogInformation(_conversionHandler.UsersAdded > 0 ? $"Done, added {_conversionHandler.UsersAdded} user(s)" : "Done, no new users were added");
				}
			});
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
        }

		private void SubscribeToAuditService()
		{
			_client.ChannelCreated += (channel) => _eventService.ChannelCreated(channel);
			_client.ChannelDestroyed += (channel) => _eventService.ChannelDestroyed(channel);
			_client.ChannelUpdated += (before, after) => _eventService.ChannelUpdated(before, after);

			_client.GuildMemberUpdated += (before, after) => _eventService.GuildMemberUpdated(before, after);
			_client.GuildUpdated += (before, after) => _eventService.GuildUpdated(before, after);

			_client.RoleCreated += (role) => _eventService.RoleCreated(role);
			_client.RoleDeleted += (role) => _eventService.RoleDeleted(role);
			_client.RoleUpdated += (before, after) => _eventService.RoleUpdated(before, after);

			_client.UserBanned += (user, guild) => _eventService.UserBanned(user, guild);
			_client.UserJoined += (user) => _eventService.UserJoined(user);
			_client.UserLeft += (user) => _eventService.UserLeft(user);
			_client.UserUnbanned += (user, guild) => _eventService.UserUnbanned(user, guild);
			_client.UserUpdated += (before, after) => _eventService.UserUpdated(before, after);
		}
	}
}
